/*Auto-generated by: https://github.com/pmndrs/gltfjsx*/

import React from "react";
import { useGLTF } from "@react-three/drei";

type FrenchCoatHangerProps = {
    color: string,
    props: string;
}
export function FrenchCoatHanger({ color, ...props }: FrenchCoatHangerProps) {
    const { nodes, materials } = useGLTF("./public/french_coat_hanger.glb");
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    geometry={nodes.Mesh_Mesh_head_geo001_lambert2SG001.geometry}
                    material={materials["lambert2SG.001"]}
                />
            </group>
        </group>
    );
}

useGLTF.preload("./public/french_coat_hanger.glb");